name: final_proj
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.5+3  
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.4
  intl: ^0.16.1
  cached_network_image: ^2.0.0
  flappy_search_bar: ^1.4.1
  slider_button: ^0.0.32
  flutter_svg: ^0.17.4
  flutter_datetime_picker: ^1.3.8
  uuid : ^2.0.4
  url_launcher: ^3.0.1
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+1
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  auto_size_text: ^2.1.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

flutter_launcher_name:
  name: "D-com"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - images/patient-min.png
    - images/menu.svg
    - images/med.png
    - images/med_logo.png
    - images/half_doctor.png
    - images/half_patient.png
    - images/VT.png
  fonts:  
   - family: Pacifico  
     fonts:  
       - asset: fonts/Pacifico-Regular.ttf   
